# Generated by Django 3.1.3 on 2020-11-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=3)),
                ('univ', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField(max_length=100)),
                ('em', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
