# Generated by Django 3.1.3 on 2020-11-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201126_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regist',
            old_name='univ',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='regist',
            name='DOB',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
