# Generated by Django 3.1.3 on 2020-12-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='img',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
